export default {
    products: [
        {
        _id: '1',
        name: 'Pink Soap',
        category: 'bars',
        image: '/images/di.jpg',
        price: 10,
        brand: 'Soapy Suds',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id: '2',
        name: 'Blue Soap',
        category: 'bars',
        image: '/images/d2.jpg',
        price: 10,
        brand: 'Soapy Suds',
        rating: 4.5,
        numReviews: 10,
        countInStock: 9,
    },
    {
        _id: '3',
        name: 'White Soap',
        category: 'bars',
        image: '/images/d3.jpg',
        price: 10,
        brand: 'Soapy Suds',
        rating: 4.5,
        numReviews: 10,
        countInStock: 3,
    },
    {
        _id: '4',
        name: 'Orange Soap',
        category: 'bars',
        image: '/images/d4.jpg',
        price: 10,
        brand: 'Soapy Suds',
        rating: 4.5,
        numReviews: 10,
        countInStock: 15,
    },
    {
        _id: '5',
        name: 'Black Soap',
        category: 'bars',
        image: '/images/d5.jpg',
        price: 10,
        brand: 'Soapy Suds',
        rating: 4.5,
        numReviews: 10,
        countInStock: 2,
    },
    {
        _id: '6',
        name: 'Yellow Soap',
        category: 'bars',
        image: '/images/d6.jpg',
        price: 10,
        brand: 'Soapy Suds',
        rating: 4.5,
        numReviews: 10,
        countInStock: 27,
    }
]
}